title: "Computing Education Research at Emeris (CERE)"
description: "Advancing computing education through research, innovation, and evidence-based practice."
theme: minima
markdown: kramdown

header_pages:
  - index.md
  - home.md
  - about.md
  - projects.md
  - people.md
  - contact.md